[package]
name = "streamserver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.81", features = ["backtrace"] }
clap = { version = "4.5.2", features = ["derive"] }
config = { version = "0.14.0", features = ["toml"] }
dirs = "5.0.1"
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "sync", "io-std", "io-util", "tracing"] }
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["json", "local-time"] }
volo = "0.9.0"
volo-grpc = "0.9.3"
